package com.ngc.salesforceplaywright.playwrightngc.locators;
import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Page;

import lombok.Getter;

@Getter
public class LeadPageLocators {
    private final Locator salutationLocator;
    private final Locator leadStatusLocator;
    private final Locator firstNameLocator;
    private final Locator middleNameLocator;
    private final Locator lastNameLocator;
    private final Locator mobileLocator;
    private final Locator emailLocator;
    private final Locator dbaNameLocator;
    private final Locator faxLocator;
    private final Locator titleLocator;
    private final Locator doNotCallLocator;
    private final Locator auctionAccessNumberLocator;
    private final Locator emailOptOutLocator;
    private final Locator preferredLanguageLocator;
    private final Locator disinterestReasonLocator;
    private final Locator preferredMethodOfCommunicationLocator;
    private final Locator disqualificationReasonLocator;
    private final Locator applicationHelpRequestedLocator;
    private final Locator helpRequestedOnLocator;
    private final Locator isALicensedDealerLocator;
    private final Locator awaitingCreditApprovalLocator;
    private final Locator salesExecutiveLocator;
    private final Locator marketLocator;
    private final Locator portfolioManagerLocator;
    private final Locator timeZoneLocator;
    private final Locator websiteLocator;
    private final Locator countryLocator;
    private final Locator streetLocator;
    private final Locator cityLocator;
    private final Locator stateLocator;
    private final Locator zipLocator;
    private final Locator countyLocator;
    private final Locator opportunityLevelLocator;
    private final Locator phoneLocator;
    private final Locator businessNameLocator;
    private final Locator cadenceRecommDateLocator;
    private final Locator leadCadenceLocator;
    private final Locator salesOpportunityLocator;
    private final Locator leadSourceLocator;
    private final Locator dealerTypeLocator;
    private final Locator driverLicenseNumberLocator;
    private final Locator lineOfCreditLocator;
    private final Locator descriptionLocator;
    private final Locator ngenContractIdLocator;
    private final Locator leadOwnerLocator;
    private final Locator bottomRowSaveButtonLocator;
    private final Locator bottomRowSaveAndNewButton;
    private final Locator bottomRowCancelButton;
    
    public LeadPageLocators(Page page) {
        this.salutationLocator = page.locator("text=Salutation");
        this.leadStatusLocator = page.locator("text=*Lead Status");
        this.firstNameLocator = page.locator("text=First Name");
        this.middleNameLocator = page.locator("text=Middle Name");
        this.cadenceRecommDateLocator = page.locator("text=Cadence Recomm Date");
        this.leadCadenceLocator = page.locator("text=Lead Cadence");
        this.salesOpportunityLocator = page.locator("label:has-text(\"Sales Opportunity\")");
        this.lastNameLocator = page.locator("text=Last Name");
        this.opportunityLevelLocator = page.locator("label:has-text(\"Opportunity Level\")");
        this.phoneLocator = page.locator("text=*Phone");
        this.businessNameLocator = page.locator("text=*Business Name");
        this.mobileLocator = page.locator("text=Mobile");
        this.emailLocator = page.locator("text=Email").first();
        this.dbaNameLocator = page.locator("text=DBA Name");
        this.faxLocator = page.locator("text=Fax");
        this.titleLocator = page.locator("text=Title");
        this.doNotCallLocator = page.locator("text=Do Not Call");
        this.auctionAccessNumberLocator = page.locator("text=Auction Access Number");
        this.emailOptOutLocator = page.locator("text=Email Opt Out");
        this.preferredLanguageLocator = page.locator("text=Preferred Language");
        this.disinterestReasonLocator = page.locator("text=Disinterest Reason");
        this.preferredMethodOfCommunicationLocator = page.locator("text=Preferred Method of Communication");
        this.disqualificationReasonLocator = page.locator("text=Disqualification Reason");
        this.applicationHelpRequestedLocator = page.locator("text=Application Help Requested");
        this.helpRequestedOnLocator = page.locator("text=Help Requested On");
        this.isALicensedDealerLocator = page.locator("text=Is a Licensed Dealer?");
        this.awaitingCreditApprovalLocator = page.locator("label:has-text(\"Awaiting Credit Approval\")");
        this.portfolioManagerLocator = page.locator("label:has-text(\"Portfolio Manager\")");
        this.salesExecutiveLocator = page.locator("text=Sales Executive");
        this.marketLocator = page.locator("label:has-text(\"Market\")");
        this.timeZoneLocator = page.locator("text=Time Zone");
        this.websiteLocator = page.locator("text=Website");
        this.countryLocator = page.locator("label:has-text(\"Country\")");
        this.streetLocator = page.locator("text=Street");
        this.stateLocator = page.locator("label:has-text(\"State/Province\")");
        this.cityLocator = page.locator("text=City");
        this.zipLocator = page.locator("text=Zip/Postal Code");
        this.countyLocator = page.locator("text=County");
        this.leadSourceLocator = page.locator("text=*Lead Source");
        this.dealerTypeLocator = page.locator("text=Dealer Type");
        this.driverLicenseNumberLocator = page.locator("text=Dealer License Number");
        this.lineOfCreditLocator = page.locator("text=Line Of Credit");
        this.descriptionLocator = page.locator("text=Description");
        this.ngenContractIdLocator = page.locator("text=NGEN Contract ID");
        this.leadOwnerLocator = page.locator("text=Lead Owner");
        this.bottomRowSaveButtonLocator = page.locator("#bottomButtonRow input[name=\"save\"]");
        this.bottomRowSaveAndNewButton = page.locator("#bottomButtonRow >> text=Save & New");
        this.bottomRowCancelButton = page.locator("#bottomButtonRow >> text=Cancel");
    }
}
